spring.application.name=ganaderia


# MySQL Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081

app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}

# Observability / Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# Logging Pattern with Traceability
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.FFF} [%thread] %-5level %logger{36} [%X{traceId:-},%X{spanId:-}] - %msg%n
logging.level.com.ganaderia=INFO
